name: Redeploy on Master Merge

on:
  push:
    branches:
      - master

jobs:
  redeploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Execute Redeploy Script on Remote Machine
      uses: appleboy/ssh-action@v0.1.8
      with:
        host: ${{ secrets.10.0.0.33 }}
        username: ${{ secrets.genserver }}
        key: ${{ secrets.REMOTE_PRIVATE_KEY }}
        port: ${{ secrets.22 }}
        script: |
          /home/genserver/redeploy.sh
